// This file is generated by the utils/IANAServicePortsGenerator.swift script.
//
// The source of truth is the IANA Service Name and Transport Protocol Port Number
// Registry, whose management procedures are defined in IETF RFC 6335 (BCP 165).
//
// https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml
// https://datatracker.ietf.org/doc/html/rfc6335
//
// Only registrations that the registry backs with a published RFC are emitted.

extension Port {
    /// The IANA `discard` service port, 9.
    ///
    /// Discard
    ///
    /// Registered for dccp, sctp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4340](https://datatracker.ietf.org/doc/html/rfc4340) and
    /// [IETF RFC 9260](https://datatracker.ietf.org/doc/html/rfc9260).
    @inlinable
    public static var discard: Self {
        Port(canonicalValue: 9)
    }

    /// The IANA `daytime` service port, 13.
    ///
    /// Daytime
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 867](https://datatracker.ietf.org/doc/html/rfc867).
    @inlinable
    public static var daytime: Self {
        Port(canonicalValue: 13)
    }

    /// The IANA `ftp-data` service port, 20.
    ///
    /// File Transfer [Default Data]
    ///
    /// Registered for sctp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 9260](https://datatracker.ietf.org/doc/html/rfc9260).
    @inlinable
    public static var `ftp-data`: Self {
        Port(canonicalValue: 20)
    }

    /// The IANA `ftp` service port, 21.
    ///
    /// File Transfer Protocol [Control]
    ///
    /// Registered for sctp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 9260](https://datatracker.ietf.org/doc/html/rfc9260) and
    /// [IETF RFC 959](https://datatracker.ietf.org/doc/html/rfc959).
    @inlinable
    public static var ftp: Self {
        Port(canonicalValue: 21)
    }

    /// The IANA `ssh` service port, 22.
    ///
    /// The Secure Shell (SSH) Protocol
    ///
    /// Registered for sctp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4251](https://datatracker.ietf.org/doc/html/rfc4251) and
    /// [IETF RFC 9260](https://datatracker.ietf.org/doc/html/rfc9260).
    @inlinable
    public static var ssh: Self {
        Port(canonicalValue: 22)
    }

    /// The IANA `telnet` service port, 23.
    ///
    /// Telnet
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 854](https://datatracker.ietf.org/doc/html/rfc854).
    @inlinable
    public static var telnet: Self {
        Port(canonicalValue: 23)
    }

    /// The IANA `bootps` service port, 67.
    ///
    /// Bootstrap Protocol Server
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 951](https://datatracker.ietf.org/doc/html/rfc951).
    @inlinable
    public static var bootps: Self {
        Port(canonicalValue: 67)
    }

    /// The IANA `http` service port, 80.
    ///
    /// World Wide Web HTTP
    ///
    /// Registered for sctp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 9110](https://datatracker.ietf.org/doc/html/rfc9110) and
    /// [IETF RFC 9260](https://datatracker.ietf.org/doc/html/rfc9260).
    @inlinable
    public static var http: Self {
        Port(canonicalValue: 80)
    }

    /// The IANA `www` service port, 80.
    ///
    /// World Wide Web HTTP
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 9110](https://datatracker.ietf.org/doc/html/rfc9110).
    @inlinable
    public static var www: Self {
        Port(canonicalValue: 80)
    }

    /// The IANA `kerberos` service port, 88.
    ///
    /// Kerberos
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4120](https://datatracker.ietf.org/doc/html/rfc4120).
    @inlinable
    public static var kerberos: Self {
        Port(canonicalValue: 88)
    }

    /// The IANA `nntp` service port, 119.
    ///
    /// Network News Transfer Protocol
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3977](https://datatracker.ietf.org/doc/html/rfc3977).
    @inlinable
    public static var nntp: Self {
        Port(canonicalValue: 119)
    }

    /// The IANA `ntp` service port, 123.
    ///
    /// Network Time Protocol
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5905](https://datatracker.ietf.org/doc/html/rfc5905).
    @inlinable
    public static var ntp: Self {
        Port(canonicalValue: 123)
    }

    /// The IANA `imap` service port, 143.
    ///
    /// Internet Message Access Protocol
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 3501](https://datatracker.ietf.org/doc/html/rfc3501) and
    /// [IETF RFC 9051](https://datatracker.ietf.org/doc/html/rfc9051).
    @inlinable
    public static var imap: Self {
        Port(canonicalValue: 143)
    }

    /// The IANA `bgp` service port, 179.
    ///
    /// Border Gateway Protocol
    ///
    /// Registered for sctp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 9260](https://datatracker.ietf.org/doc/html/rfc9260).
    @inlinable
    public static var bgp: Self {
        Port(canonicalValue: 179)
    }

    /// The IANA `manet` service port, 269.
    ///
    /// MANET Protocols
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5498](https://datatracker.ietf.org/doc/html/rfc5498).
    @inlinable
    public static var manet: Self {
        Port(canonicalValue: 269)
    }

    /// The IANA `gist` service port, 270.
    ///
    /// Q-mode encapsulation for GIST messages
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 5971](https://datatracker.ietf.org/doc/html/rfc5971).
    @inlinable
    public static var gist: Self {
        Port(canonicalValue: 270)
    }

    /// The IANA `pt-tls` service port, 271.
    ///
    /// IETF Network Endpoint Assessment (NEA) Posture Transport Protocol over TLS (PT-TLS)
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 6876](https://datatracker.ietf.org/doc/html/rfc6876).
    @inlinable
    public static var `pt-tls`: Self {
        Port(canonicalValue: 271)
    }

    /// The IANA `tacacss` service port, 300.
    ///
    /// TLS Secure Login Host Protocol (TACACSS)
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 9887](https://datatracker.ietf.org/doc/html/rfc9887).
    @inlinable
    public static var tacacss: Self {
        Port(canonicalValue: 300)
    }

    /// The IANA `rpki-rtr` service port, 323.
    ///
    /// Resource PKI to Router Protocol
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 6810](https://datatracker.ietf.org/doc/html/rfc6810).
    @inlinable
    public static var `rpki-rtr`: Self {
        Port(canonicalValue: 323)
    }

    /// The IANA `rpki-rtr-tls` service port, 324.
    ///
    /// Resource PKI to Router Protocol over TLS
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 6810](https://datatracker.ietf.org/doc/html/rfc6810).
    @inlinable
    public static var `rpki-rtr-tls`: Self {
        Port(canonicalValue: 324)
    }

    /// The IANA `matip-type-a` service port, 350.
    ///
    /// MATIP Type A
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 2351](https://datatracker.ietf.org/doc/html/rfc2351).
    @inlinable
    public static var `matip-type-a`: Self {
        Port(canonicalValue: 350)
    }

    /// The IANA `matip-type-b` service port, 351.
    ///
    /// MATIP Type B
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 2351](https://datatracker.ietf.org/doc/html/rfc2351).
    @inlinable
    public static var `matip-type-b`: Self {
        Port(canonicalValue: 351)
    }

    /// The IANA `nnsp` service port, 433.
    ///
    /// NNTP for transit servers (NNSP)
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3977](https://datatracker.ietf.org/doc/html/rfc3977).
    @inlinable
    public static var nnsp: Self {
        Port(canonicalValue: 433)
    }

    /// The IANA `https` service port, 443.
    ///
    /// http protocol over TLS/SSL
    ///
    /// Registered for sctp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 9110](https://datatracker.ietf.org/doc/html/rfc9110) and
    /// [IETF RFC 9260](https://datatracker.ietf.org/doc/html/rfc9260).
    @inlinable
    public static var https: Self {
        Port(canonicalValue: 443)
    }

    /// The IANA `snpp` service port, 444.
    ///
    /// Simple Network Paging Protocol
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 1568](https://datatracker.ietf.org/doc/html/rfc1568).
    @inlinable
    public static var snpp: Self {
        Port(canonicalValue: 444)
    }

    /// The IANA `submissions` service port, 465.
    ///
    /// Message Submission over TLS protocol
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 8314](https://datatracker.ietf.org/doc/html/rfc8314).
    @inlinable
    public static var submissions: Self {
        Port(canonicalValue: 465)
    }

    /// The IANA `syslog` service port, 514.
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 5426](https://datatracker.ietf.org/doc/html/rfc5426).
    @inlinable
    public static var syslog: Self {
        Port(canonicalValue: 514)
    }

    /// The IANA `dhcpv6-client` service port, 546.
    ///
    /// DHCPv6 Client
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 9915](https://datatracker.ietf.org/doc/html/rfc9915).
    @inlinable
    public static var `dhcpv6-client`: Self {
        Port(canonicalValue: 546)
    }

    /// The IANA `dhcpv6-server` service port, 547.
    ///
    /// DHCPv6 Server
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5460](https://datatracker.ietf.org/doc/html/rfc5460) and
    /// [IETF RFC 9915](https://datatracker.ietf.org/doc/html/rfc9915).
    @inlinable
    public static var `dhcpv6-server`: Self {
        Port(canonicalValue: 547)
    }

    /// The IANA `cybercash` service port, 551.
    ///
    /// cybercash
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 1898](https://datatracker.ietf.org/doc/html/rfc1898).
    @inlinable
    public static var cybercash: Self {
        Port(canonicalValue: 551)
    }

    /// The IANA `nntps` service port, 563.
    ///
    /// nntp protocol over TLS/SSL (was snntp)
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4642](https://datatracker.ietf.org/doc/html/rfc4642).
    @inlinable
    public static var nntps: Self {
        Port(canonicalValue: 563)
    }

    /// The IANA `submission` service port, 587.
    ///
    /// Message Submission
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 6409](https://datatracker.ietf.org/doc/html/rfc6409).
    @inlinable
    public static var submission: Self {
        Port(canonicalValue: 587)
    }

    /// The IANA `syslog-conn` service port, 601.
    ///
    /// Reliable Syslog Service
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3195](https://datatracker.ietf.org/doc/html/rfc3195).
    @inlinable
    public static var `syslog-conn`: Self {
        Port(canonicalValue: 601)
    }

    /// The IANA `xmlrpc-beep` service port, 602.
    ///
    /// XML-RPC over BEEP
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3529](https://datatracker.ietf.org/doc/html/rfc3529).
    @inlinable
    public static var `xmlrpc-beep`: Self {
        Port(canonicalValue: 602)
    }

    /// The IANA `idxp` service port, 603.
    ///
    /// IDXP
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4767](https://datatracker.ietf.org/doc/html/rfc4767).
    @inlinable
    public static var idxp: Self {
        Port(canonicalValue: 603)
    }

    /// The IANA `tunnel` service port, 604.
    ///
    /// TUNNEL
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3620](https://datatracker.ietf.org/doc/html/rfc3620).
    @inlinable
    public static var tunnel: Self {
        Port(canonicalValue: 604)
    }

    /// The IANA `soap-beep` service port, 605.
    ///
    /// SOAP over BEEP
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4227](https://datatracker.ietf.org/doc/html/rfc4227).
    @inlinable
    public static var `soap-beep`: Self {
        Port(canonicalValue: 605)
    }

    /// The IANA `ipp` service port, 631.
    ///
    /// IPP (Internet Printing Protocol)
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 8011](https://datatracker.ietf.org/doc/html/rfc8011).
    @inlinable
    public static var ipp: Self {
        Port(canonicalValue: 631)
    }

    /// The IANA `ipps` service port, 631.
    ///
    /// Internet Printing Protocol over HTTPS
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 8011](https://datatracker.ietf.org/doc/html/rfc8011).
    @inlinable
    public static var ipps: Self {
        Port(canonicalValue: 631)
    }

    /// The IANA `dhcp-failover` service port, 647.
    ///
    /// DHCP Failover
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 8156](https://datatracker.ietf.org/doc/html/rfc8156).
    @inlinable
    public static var `dhcp-failover`: Self {
        Port(canonicalValue: 647)
    }

    /// The IANA `epp` service port, 700.
    ///
    /// Extensible Provisioning Protocol
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in RFC-ietf-regext-epp-quic-12 and
    /// [IETF RFC 5734](https://datatracker.ietf.org/doc/html/rfc5734).
    @inlinable
    public static var epp: Self {
        Port(canonicalValue: 700)
    }

    /// The IANA `lmp` service port, 701.
    ///
    /// Link Management Protocol (LMP)
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4204](https://datatracker.ietf.org/doc/html/rfc4204).
    @inlinable
    public static var lmp: Self {
        Port(canonicalValue: 701)
    }

    /// The IANA `iris-beep` service port, 702.
    ///
    /// IRIS over BEEP
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3983](https://datatracker.ietf.org/doc/html/rfc3983).
    @inlinable
    public static var `iris-beep`: Self {
        Port(canonicalValue: 702)
    }

    /// The IANA `tbrpf` service port, 712.
    ///
    /// TBRPF
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3684](https://datatracker.ietf.org/doc/html/rfc3684).
    @inlinable
    public static var tbrpf: Self {
        Port(canonicalValue: 712)
    }

    /// The IANA `iris-xpcs` service port, 714.
    ///
    /// IRIS over XPCS
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4992](https://datatracker.ietf.org/doc/html/rfc4992).
    @inlinable
    public static var `iris-xpcs`: Self {
        Port(canonicalValue: 714)
    }

    /// The IANA `iris-lwz` service port, 715.
    ///
    /// IRIS-LWZ
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4993](https://datatracker.ietf.org/doc/html/rfc4993).
    @inlinable
    public static var `iris-lwz`: Self {
        Port(canonicalValue: 715)
    }

    /// The IANA `pana` service port, 716.
    ///
    /// PANA Messages
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 5191](https://datatracker.ietf.org/doc/html/rfc5191).
    @inlinable
    public static var pana: Self {
        Port(canonicalValue: 716)
    }

    /// The IANA `netconf-ssh` service port, 830.
    ///
    /// NETCONF over SSH
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 6242](https://datatracker.ietf.org/doc/html/rfc6242).
    @inlinable
    public static var `netconf-ssh`: Self {
        Port(canonicalValue: 830)
    }

    /// The IANA `gdoi` service port, 848.
    ///
    /// GDOI
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3547](https://datatracker.ietf.org/doc/html/rfc3547).
    @inlinable
    public static var gdoi: Self {
        Port(canonicalValue: 848)
    }

    /// The IANA `domain-s` service port, 853.
    ///
    /// DNS query-response protocol run over TLS
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 7858](https://datatracker.ietf.org/doc/html/rfc7858),
    /// [IETF RFC 8094](https://datatracker.ietf.org/doc/html/rfc8094) and
    /// [IETF RFC 9250](https://datatracker.ietf.org/doc/html/rfc9250).
    @inlinable
    public static var `domain-s`: Self {
        Port(canonicalValue: 853)
    }

    /// The IANA `dlep` service port, 854.
    ///
    /// Dynamic Link Exchange Protocol (DLEP)
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 8175](https://datatracker.ietf.org/doc/html/rfc8175).
    @inlinable
    public static var dlep: Self {
        Port(canonicalValue: 854)
    }

    /// The IANA `iscsi` service port, 860.
    ///
    /// iSCSI
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 7143](https://datatracker.ietf.org/doc/html/rfc7143).
    @inlinable
    public static var iscsi: Self {
        Port(canonicalValue: 860)
    }

    /// The IANA `owamp-control` service port, 861.
    ///
    /// OWAMP-Control
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 4656](https://datatracker.ietf.org/doc/html/rfc4656).
    @inlinable
    public static var `owamp-control`: Self {
        Port(canonicalValue: 861)
    }

    /// The IANA `owamp-test` service port, 861.
    ///
    /// OWAMP-Test
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 8545](https://datatracker.ietf.org/doc/html/rfc8545).
    @inlinable
    public static var `owamp-test`: Self {
        Port(canonicalValue: 861)
    }

    /// The IANA `twamp-control` service port, 862.
    ///
    /// TWAMP-Control
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 5357](https://datatracker.ietf.org/doc/html/rfc5357).
    @inlinable
    public static var `twamp-control`: Self {
        Port(canonicalValue: 862)
    }

    /// The IANA `twamp-test` service port, 862.
    ///
    /// TWAMP-Test Receiver Port
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 8545](https://datatracker.ietf.org/doc/html/rfc8545).
    @inlinable
    public static var `twamp-test`: Self {
        Port(canonicalValue: 862)
    }

    /// The IANA `kink` service port, 910.
    ///
    /// Kerberized Internet Negotiation of Keys (KINK)
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4430](https://datatracker.ietf.org/doc/html/rfc4430).
    @inlinable
    public static var kink: Self {
        Port(canonicalValue: 910)
    }

    /// The IANA `apex-edge` service port, 913.
    ///
    /// APEX endpoint-relay service
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3340](https://datatracker.ietf.org/doc/html/rfc3340).
    @inlinable
    public static var `apex-edge`: Self {
        Port(canonicalValue: 913)
    }

    /// The IANA `rift-lies` service port, 914.
    ///
    /// Routing in Fat Trees Link Information Element
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 9692](https://datatracker.ietf.org/doc/html/rfc9692).
    @inlinable
    public static var `rift-lies`: Self {
        Port(canonicalValue: 914)
    }

    /// The IANA `rift-ties` service port, 915.
    ///
    /// Routing in Fat Trees Topology Information Element
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 9692](https://datatracker.ietf.org/doc/html/rfc9692).
    @inlinable
    public static var `rift-ties`: Self {
        Port(canonicalValue: 915)
    }

    /// The IANA `nas` service port, 991.
    ///
    /// Netnews Administration System
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4707](https://datatracker.ietf.org/doc/html/rfc4707).
    @inlinable
    public static var nas: Self {
        Port(canonicalValue: 991)
    }

    /// The IANA `imaps` service port, 993.
    ///
    /// IMAP over TLS protocol
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 3501](https://datatracker.ietf.org/doc/html/rfc3501),
    /// [IETF RFC 8314](https://datatracker.ietf.org/doc/html/rfc8314) and
    /// [IETF RFC 9051](https://datatracker.ietf.org/doc/html/rfc9051).
    @inlinable
    public static var imaps: Self {
        Port(canonicalValue: 993)
    }

    /// The IANA `pop3s` service port, 995.
    ///
    /// POP3 over TLS protocol
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 8314](https://datatracker.ietf.org/doc/html/rfc8314).
    @inlinable
    public static var pop3s: Self {
        Port(canonicalValue: 995)
    }

    /// The IANA `webpush` service port, 1001.
    ///
    /// HTTP Web Push
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 8030](https://datatracker.ietf.org/doc/html/rfc8030).
    @inlinable
    public static var webpush: Self {
        Port(canonicalValue: 1001)
    }

    /// The IANA `exp1` service port, 1021.
    ///
    /// RFC3692-style Experiment 1
    ///
    /// Registered for dccp, sctp, tcp and udp transport protocols.
    ///
    /// Defined in 1, [IETF RFC 4727](https://datatracker.ietf.org/doc/html/rfc4727) and
    /// [IETF RFC 6335](https://datatracker.ietf.org/doc/html/rfc6335).
    @inlinable
    public static var exp1: Self {
        Port(canonicalValue: 1021)
    }

    /// The IANA `exp2` service port, 1022.
    ///
    /// RFC3692-style Experiment 2
    ///
    /// Registered for dccp, sctp, tcp and udp transport protocols.
    ///
    /// Defined in 1, [IETF RFC 4727](https://datatracker.ietf.org/doc/html/rfc4727) and
    /// [IETF RFC 6335](https://datatracker.ietf.org/doc/html/rfc6335).
    @inlinable
    public static var exp2: Self {
        Port(canonicalValue: 1022)
    }

    /// The IANA `6a44` service port, 1027.
    ///
    /// IPv6 Behind NAT44 CPEs
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 6751](https://datatracker.ietf.org/doc/html/rfc6751).
    @inlinable
    public static var `6a44`: Self {
        Port(canonicalValue: 1027)
    }

    /// The IANA `mtqp` service port, 1038.
    ///
    /// Message Tracking Query Protocol
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3887](https://datatracker.ietf.org/doc/html/rfc3887).
    @inlinable
    public static var mtqp: Self {
        Port(canonicalValue: 1038)
    }

    /// The IANA `ltp-deepspace` service port, 1113.
    ///
    /// Licklider Transmission Protocol
    ///
    /// Registered for dccp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5326](https://datatracker.ietf.org/doc/html/rfc5326) and
    /// [IETF RFC 7122](https://datatracker.ietf.org/doc/html/rfc7122).
    @inlinable
    public static var `ltp-deepspace`: Self {
        Port(canonicalValue: 1113)
    }

    /// The IANA `sacred` service port, 1118.
    ///
    /// SACRED
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3767](https://datatracker.ietf.org/doc/html/rfc3767).
    @inlinable
    public static var sacred: Self {
        Port(canonicalValue: 1118)
    }

    /// The IANA `c1222-acse` service port, 1153.
    ///
    /// ANSI C12.22 Port
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 6142](https://datatracker.ietf.org/doc/html/rfc6142).
    @inlinable
    public static var `c1222-acse`: Self {
        Port(canonicalValue: 1153)
    }

    /// The IANA `pptp` service port, 1723.
    ///
    /// pptp
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 2637](https://datatracker.ietf.org/doc/html/rfc2637).
    @inlinable
    public static var pptp: Self {
        Port(canonicalValue: 1723)
    }

    /// The IANA `radius` service port, 1812.
    ///
    /// RADIUS
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 2865](https://datatracker.ietf.org/doc/html/rfc2865).
    @inlinable
    public static var radius: Self {
        Port(canonicalValue: 1812)
    }

    /// The IANA `radius-acct` service port, 1813.
    ///
    /// RADIUS Accounting
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 2866](https://datatracker.ietf.org/doc/html/rfc2866).
    @inlinable
    public static var `radius-acct`: Self {
        Port(canonicalValue: 1813)
    }

    /// The IANA `slp-notify` service port, 1847.
    ///
    /// SLP Notification
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3082](https://datatracker.ietf.org/doc/html/rfc3082).
    @inlinable
    public static var `slp-notify`: Self {
        Port(canonicalValue: 1847)
    }

    /// The IANA `hsrp` service port, 1985.
    ///
    /// Hot Standby Router Protocol
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 2281](https://datatracker.ietf.org/doc/html/rfc2281).
    @inlinable
    public static var hsrp: Self {
        Port(canonicalValue: 1985)
    }

    /// The IANA `nfs` service port, 2049.
    ///
    /// Network File System - Sun Microsystems
    ///
    /// Registered for sctp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5665](https://datatracker.ietf.org/doc/html/rfc5665).
    @inlinable
    public static var nfs: Self {
        Port(canonicalValue: 2049)
    }

    /// The IANA `radsec` service port, 2083.
    ///
    /// Secure Radius Service
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 6614](https://datatracker.ietf.org/doc/html/rfc6614) and
    /// [IETF RFC 7360](https://datatracker.ietf.org/doc/html/rfc7360).
    @inlinable
    public static var radsec: Self {
        Port(canonicalValue: 2083)
    }

    /// The IANA `tdmoip` service port, 2142.
    ///
    /// TDM OVER IP
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5087](https://datatracker.ietf.org/doc/html/rfc5087).
    @inlinable
    public static var tdmoip: Self {
        Port(canonicalValue: 2142)
    }

    /// The IANA `amt` service port, 2268.
    ///
    /// AMT
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 7450](https://datatracker.ietf.org/doc/html/rfc7450).
    @inlinable
    public static var amt: Self {
        Port(canonicalValue: 2268)
    }

    /// The IANA `msrp` service port, 2855.
    ///
    /// MSRP over TCP
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 4976](https://datatracker.ietf.org/doc/html/rfc4976).
    @inlinable
    public static var msrp: Self {
        Port(canonicalValue: 2855)
    }

    /// The IANA `m3ua` service port, 2905.
    ///
    /// M3UA
    ///
    /// Registered for sctp and tcp transport protocols.
    ///
    /// Defined in [IETF RFC 4666](https://datatracker.ietf.org/doc/html/rfc4666).
    @inlinable
    public static var m3ua: Self {
        Port(canonicalValue: 2905)
    }

    /// The IANA `isns` service port, 3205.
    ///
    /// iSNS Server Port
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4171](https://datatracker.ietf.org/doc/html/rfc4171).
    @inlinable
    public static var isns: Self {
        Port(canonicalValue: 3205)
    }

    /// The IANA `fcip-port` service port, 3225.
    ///
    /// FCIP
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3821](https://datatracker.ietf.org/doc/html/rfc3821).
    @inlinable
    public static var `fcip-port`: Self {
        Port(canonicalValue: 3225)
    }

    /// The IANA `mdtp` service port, 3232.
    ///
    /// MDT port
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 6513](https://datatracker.ietf.org/doc/html/rfc6513).
    @inlinable
    public static var mdtp: Self {
        Port(canonicalValue: 3232)
    }

    /// The IANA `iscsi-target` service port, 3260.
    ///
    /// iSCSI port
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 7143](https://datatracker.ietf.org/doc/html/rfc7143).
    @inlinable
    public static var `iscsi-target`: Self {
        Port(canonicalValue: 3260)
    }

    /// The IANA `odette-ftp` service port, 3305.
    ///
    /// ODETTE-FTP
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5024](https://datatracker.ietf.org/doc/html/rfc5024).
    @inlinable
    public static var `odette-ftp`: Self {
        Port(canonicalValue: 3305)
    }

    /// The IANA `ifcp-port` service port, 3420.
    ///
    /// iFCP User Port
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4172](https://datatracker.ietf.org/doc/html/rfc4172).
    @inlinable
    public static var `ifcp-port`: Self {
        Port(canonicalValue: 3420)
    }

    /// The IANA `stun` service port, 3478.
    ///
    /// Session Traversal Utilities for NAT (STUN) port
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 8489](https://datatracker.ietf.org/doc/html/rfc8489).
    @inlinable
    public static var stun: Self {
        Port(canonicalValue: 3478)
    }

    /// The IANA `stun-behavior` service port, 3478.
    ///
    /// STUN Behavior Discovery over TCP
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5780](https://datatracker.ietf.org/doc/html/rfc5780).
    @inlinable
    public static var `stun-behavior`: Self {
        Port(canonicalValue: 3478)
    }

    /// The IANA `turn` service port, 3478.
    ///
    /// TURN over TCP
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 8656](https://datatracker.ietf.org/doc/html/rfc8656).
    @inlinable
    public static var turn: Self {
        Port(canonicalValue: 3478)
    }

    /// The IANA `nut` service port, 3493.
    ///
    /// Network UPS Tools
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 9271](https://datatracker.ietf.org/doc/html/rfc9271).
    @inlinable
    public static var nut: Self {
        Port(canonicalValue: 3493)
    }

    /// The IANA `lsp-ping` service port, 3503.
    ///
    /// MPLS LSP-echo Port
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 8029](https://datatracker.ietf.org/doc/html/rfc8029).
    @inlinable
    public static var `lsp-ping`: Self {
        Port(canonicalValue: 3503)
    }

    /// The IANA `teredo` service port, 3544.
    ///
    /// Teredo Port
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4380](https://datatracker.ietf.org/doc/html/rfc4380).
    @inlinable
    public static var teredo: Self {
        Port(canonicalValue: 3544)
    }

    /// The IANA `m2pa` service port, 3565.
    ///
    /// M2PA
    ///
    /// Registered for sctp and tcp transport protocols.
    ///
    /// Defined in [IETF RFC 4165](https://datatracker.ietf.org/doc/html/rfc4165).
    @inlinable
    public static var m2pa: Self {
        Port(canonicalValue: 3565)
    }

    /// The IANA `tsp` service port, 3653.
    ///
    /// Tunnel Setup Protocol
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5572](https://datatracker.ietf.org/doc/html/rfc5572).
    @inlinable
    public static var tsp: Self {
        Port(canonicalValue: 3653)
    }

    /// The IANA `gsakmp` service port, 3761.
    ///
    /// gsakmp port
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4535](https://datatracker.ietf.org/doc/html/rfc4535).
    @inlinable
    public static var gsakmp: Self {
        Port(canonicalValue: 3761)
    }

    /// The IANA `bfd-control` service port, 3784.
    ///
    /// BFD Control Protocol
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5881](https://datatracker.ietf.org/doc/html/rfc5881).
    @inlinable
    public static var `bfd-control`: Self {
        Port(canonicalValue: 3784)
    }

    /// The IANA `bfd-echo` service port, 3785.
    ///
    /// BFD Echo Protocol
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5881](https://datatracker.ietf.org/doc/html/rfc5881).
    @inlinable
    public static var `bfd-echo`: Self {
        Port(canonicalValue: 3785)
    }

    /// The IANA `radius-dynauth` service port, 3799.
    ///
    /// RADIUS Dynamic Authorization
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3576](https://datatracker.ietf.org/doc/html/rfc3576).
    @inlinable
    public static var `radius-dynauth`: Self {
        Port(canonicalValue: 3799)
    }

    /// The IANA `asap-sctp` service port, 3863.
    ///
    /// asap sctp
    ///
    /// Registered for sctp transport protocol.
    ///
    /// Defined in [IETF RFC 5352](https://datatracker.ietf.org/doc/html/rfc5352).
    @inlinable
    public static var `asap-sctp`: Self {
        Port(canonicalValue: 3863)
    }

    /// The IANA `asap-udp` service port, 3863.
    ///
    /// asap udp port
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 5352](https://datatracker.ietf.org/doc/html/rfc5352).
    @inlinable
    public static var `asap-udp`: Self {
        Port(canonicalValue: 3863)
    }

    /// The IANA `asap-sctp-tls` service port, 3864.
    ///
    /// asap-sctp/tls
    ///
    /// Registered for sctp transport protocol.
    ///
    /// Defined in [IETF RFC 5352](https://datatracker.ietf.org/doc/html/rfc5352).
    @inlinable
    public static var `asap-sctp-tls`: Self {
        Port(canonicalValue: 3864)
    }

    /// The IANA `asap-tcp-tls` service port, 3864.
    ///
    /// asap/tls tcp port
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 5352](https://datatracker.ietf.org/doc/html/rfc5352).
    @inlinable
    public static var `asap-tcp-tls`: Self {
        Port(canonicalValue: 3864)
    }

    /// The IANA `diameter` service port, 3868.
    ///
    /// DIAMETER
    ///
    /// Registered for sctp and tcp transport protocols.
    ///
    /// Defined in [IETF RFC 3588](https://datatracker.ietf.org/doc/html/rfc3588).
    @inlinable
    public static var diameter: Self {
        Port(canonicalValue: 3868)
    }

    /// The IANA `mupdate` service port, 3905.
    ///
    /// Mailbox Update (MUPDATE) protocol
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3656](https://datatracker.ietf.org/doc/html/rfc3656).
    @inlinable
    public static var mupdate: Self {
        Port(canonicalValue: 3905)
    }

    /// The IANA `dsmipv6` service port, 4191.
    ///
    /// Dual Stack MIPv6 NAT Traversal
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 5555](https://datatracker.ietf.org/doc/html/rfc5555).
    @inlinable
    public static var dsmipv6: Self {
        Port(canonicalValue: 4191)
    }

    /// The IANA `rwhois` service port, 4321.
    ///
    /// Remote Who Is
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 2167](https://datatracker.ietf.org/doc/html/rfc2167).
    @inlinable
    public static var rwhois: Self {
        Port(canonicalValue: 4321)
    }

    /// The IANA `netconf-ch-ssh` service port, 4334.
    ///
    /// NETCONF Call Home (SSH)
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 8071](https://datatracker.ietf.org/doc/html/rfc8071).
    @inlinable
    public static var `netconf-ch-ssh`: Self {
        Port(canonicalValue: 4334)
    }

    /// The IANA `netconf-ch-tls` service port, 4335.
    ///
    /// NETCONF Call Home (TLS)
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 8071](https://datatracker.ietf.org/doc/html/rfc8071).
    @inlinable
    public static var `netconf-ch-tls`: Self {
        Port(canonicalValue: 4335)
    }

    /// The IANA `restconf-ch-tls` service port, 4336.
    ///
    /// RESTCONF Call Home (TLS)
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 8071](https://datatracker.ietf.org/doc/html/rfc8071).
    @inlinable
    public static var `restconf-ch-tls`: Self {
        Port(canonicalValue: 4336)
    }

    /// The IANA `lisp-data` service port, 4341.
    ///
    /// LISP Data Packets
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 9300](https://datatracker.ietf.org/doc/html/rfc9300).
    @inlinable
    public static var `lisp-data`: Self {
        Port(canonicalValue: 4341)
    }

    /// The IANA `lisp-control` service port, 4342.
    ///
    /// LISP Control Packets
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 9301](https://datatracker.ietf.org/doc/html/rfc9301).
    @inlinable
    public static var `lisp-control`: Self {
        Port(canonicalValue: 4342)
    }

    /// The IANA `ntske` service port, 4460.
    ///
    /// Network Time Security Key Establishment
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 8915](https://datatracker.ietf.org/doc/html/rfc8915).
    @inlinable
    public static var ntske: Self {
        Port(canonicalValue: 4460)
    }

    /// The IANA `ipsec-nat-t` service port, 4500.
    ///
    /// IPsec NAT-Traversal
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3948](https://datatracker.ietf.org/doc/html/rfc3948),
    /// [IETF RFC 7296](https://datatracker.ietf.org/doc/html/rfc7296) and
    /// [IETF RFC 9329](https://datatracker.ietf.org/doc/html/rfc9329).
    @inlinable
    public static var `ipsec-nat-t`: Self {
        Port(canonicalValue: 4500)
    }

    /// The IANA `ieee-mih` service port, 4551.
    ///
    /// MIH Services
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5677](https://datatracker.ietf.org/doc/html/rfc5677).
    @inlinable
    public static var `ieee-mih`: Self {
        Port(canonicalValue: 4551)
    }

    /// The IANA `rsip` service port, 4555.
    ///
    /// RSIP Port
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3103](https://datatracker.ietf.org/doc/html/rfc3103).
    @inlinable
    public static var rsip: Self {
        Port(canonicalValue: 4555)
    }

    /// The IANA `dtn-bundle` service port, 4556.
    ///
    /// DTN Bundle TCP CL Protocol
    ///
    /// Registered for dccp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 7122](https://datatracker.ietf.org/doc/html/rfc7122) and
    /// [IETF RFC 9174](https://datatracker.ietf.org/doc/html/rfc9174).
    @inlinable
    public static var `dtn-bundle`: Self {
        Port(canonicalValue: 4556)
    }

    /// The IANA `iax` service port, 4569.
    ///
    /// Inter-Asterisk eXchange
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5456](https://datatracker.ietf.org/doc/html/rfc5456).
    @inlinable
    public static var iax: Self {
        Port(canonicalValue: 4569)
    }

    /// The IANA `rid` service port, 4590.
    ///
    /// RID over HTTP/TLS
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 6546](https://datatracker.ietf.org/doc/html/rfc6546).
    @inlinable
    public static var rid: Self {
        Port(canonicalValue: 4590)
    }

    /// The IANA `dots-signal` service port, 4646.
    ///
    /// Distributed Denial-of-Service Open Threat Signaling (DOTS) Signal Channel Protocol. The
    /// service name is used to construct the SRV service names "_dots-signal._udp" and
    /// "_dots-signal._tcp" for discovering DOTS servers used to establish DOTS signal channel.
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 8973](https://datatracker.ietf.org/doc/html/rfc8973) and
    /// [IETF RFC 9132](https://datatracker.ietf.org/doc/html/rfc9132).
    @inlinable
    public static var `dots-signal`: Self {
        Port(canonicalValue: 4646)
    }

    /// The IANA `gre-in-udp` service port, 4754.
    ///
    /// GRE-in-UDP Encapsulation
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 8086](https://datatracker.ietf.org/doc/html/rfc8086).
    @inlinable
    public static var `gre-in-udp`: Self {
        Port(canonicalValue: 4754)
    }

    /// The IANA `gre-udp-dtls` service port, 4755.
    ///
    /// GRE-in-UDP Encapsulation with DTLS
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 8086](https://datatracker.ietf.org/doc/html/rfc8086).
    @inlinable
    public static var `gre-udp-dtls`: Self {
        Port(canonicalValue: 4755)
    }

    /// The IANA `vxlan` service port, 4789.
    ///
    /// Virtual eXtensible Local Area Network (VXLAN)
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 7348](https://datatracker.ietf.org/doc/html/rfc7348).
    @inlinable
    public static var vxlan: Self {
        Port(canonicalValue: 4789)
    }

    /// The IANA `avt-profile-1` service port, 5004.
    ///
    /// RTP media data
    ///
    /// Registered for dccp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3551](https://datatracker.ietf.org/doc/html/rfc3551),
    /// [IETF RFC 4571](https://datatracker.ietf.org/doc/html/rfc4571) and
    /// [IETF RFC 5762](https://datatracker.ietf.org/doc/html/rfc5762).
    @inlinable
    public static var `avt-profile-1`: Self {
        Port(canonicalValue: 5004)
    }

    /// The IANA `avt-profile-2` service port, 5005.
    ///
    /// RTP control protocol
    ///
    /// Registered for dccp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3551](https://datatracker.ietf.org/doc/html/rfc3551),
    /// [IETF RFC 4571](https://datatracker.ietf.org/doc/html/rfc4571) and
    /// [IETF RFC 5762](https://datatracker.ietf.org/doc/html/rfc5762).
    @inlinable
    public static var `avt-profile-2`: Self {
        Port(canonicalValue: 5005)
    }

    /// The IANA `sip` service port, 5060.
    ///
    /// SIP
    ///
    /// Registered for sctp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3263](https://datatracker.ietf.org/doc/html/rfc3263) and
    /// [IETF RFC 4168](https://datatracker.ietf.org/doc/html/rfc4168).
    @inlinable
    public static var sip: Self {
        Port(canonicalValue: 5060)
    }

    /// The IANA `sips` service port, 5061.
    ///
    /// SIP-TLS
    ///
    /// Registered for sctp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3263](https://datatracker.ietf.org/doc/html/rfc3263) and
    /// [IETF RFC 4168](https://datatracker.ietf.org/doc/html/rfc4168).
    @inlinable
    public static var sips: Self {
        Port(canonicalValue: 5061)
    }

    /// The IANA `cxtp` service port, 5091.
    ///
    /// Context Transfer Protocol
    ///
    /// Registered for sctp transport protocol.
    ///
    /// Defined in [IETF RFC 4065](https://datatracker.ietf.org/doc/html/rfc4065).
    @inlinable
    public static var cxtp: Self {
        Port(canonicalValue: 5091)
    }

    /// The IANA `snmpssh` service port, 5161.
    ///
    /// SNMP over SSH Transport Model
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 5592](https://datatracker.ietf.org/doc/html/rfc5592).
    @inlinable
    public static var snmpssh: Self {
        Port(canonicalValue: 5161)
    }

    /// The IANA `snmpssh-trap` service port, 5162.
    ///
    /// SNMP Notification over SSH Transport Model
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 5592](https://datatracker.ietf.org/doc/html/rfc5592).
    @inlinable
    public static var `snmpssh-trap`: Self {
        Port(canonicalValue: 5162)
    }

    /// The IANA `xmpp-client` service port, 5222.
    ///
    /// XMPP Client Connection
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 6120](https://datatracker.ietf.org/doc/html/rfc6120).
    @inlinable
    public static var `xmpp-client`: Self {
        Port(canonicalValue: 5222)
    }

    /// The IANA `capwap-control` service port, 5246.
    ///
    /// CAPWAP Control Protocol
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 5415](https://datatracker.ietf.org/doc/html/rfc5415).
    @inlinable
    public static var `capwap-control`: Self {
        Port(canonicalValue: 5246)
    }

    /// The IANA `capwap-data` service port, 5247.
    ///
    /// CAPWAP Data Protocol
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 5415](https://datatracker.ietf.org/doc/html/rfc5415).
    @inlinable
    public static var `capwap-data`: Self {
        Port(canonicalValue: 5247)
    }

    /// The IANA `xmpp-server` service port, 5269.
    ///
    /// XMPP Server Connection
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 6120](https://datatracker.ietf.org/doc/html/rfc6120).
    @inlinable
    public static var `xmpp-server`: Self {
        Port(canonicalValue: 5269)
    }

    /// The IANA `pkix-cmc` service port, 5318.
    ///
    /// PKIX Certificate Management using CMS (CMC)
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 10003](https://datatracker.ietf.org/doc/html/rfc10003).
    @inlinable
    public static var `pkix-cmc`: Self {
        Port(canonicalValue: 5318)
    }

    /// The IANA `stun-behaviors` service port, 5349.
    ///
    /// STUN Behavior Discovery over TLS
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5780](https://datatracker.ietf.org/doc/html/rfc5780).
    @inlinable
    public static var `stun-behaviors`: Self {
        Port(canonicalValue: 5349)
    }

    /// The IANA `stuns` service port, 5349.
    ///
    /// Session Traversal Utilities for NAT (STUN) port
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 7350](https://datatracker.ietf.org/doc/html/rfc7350) and
    /// [IETF RFC 8489](https://datatracker.ietf.org/doc/html/rfc8489).
    @inlinable
    public static var stuns: Self {
        Port(canonicalValue: 5349)
    }

    /// The IANA `turns` service port, 5349.
    ///
    /// TURN over TLS
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 7350](https://datatracker.ietf.org/doc/html/rfc7350) and
    /// [IETF RFC 8656](https://datatracker.ietf.org/doc/html/rfc8656).
    @inlinable
    public static var turns: Self {
        Port(canonicalValue: 5349)
    }

    /// The IANA `pcp-multicast` service port, 5350.
    ///
    /// Port Control Protocol Multicast
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 6887](https://datatracker.ietf.org/doc/html/rfc6887).
    @inlinable
    public static var `pcp-multicast`: Self {
        Port(canonicalValue: 5350)
    }

    /// The IANA `pcp` service port, 5351.
    ///
    /// Port Control Protocol
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 6887](https://datatracker.ietf.org/doc/html/rfc6887).
    @inlinable
    public static var pcp: Self {
        Port(canonicalValue: 5351)
    }

    /// The IANA `dns-llq` service port, 5352.
    ///
    /// DNS Long-Lived Queries
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 8764](https://datatracker.ietf.org/doc/html/rfc8764).
    @inlinable
    public static var `dns-llq`: Self {
        Port(canonicalValue: 5352)
    }

    /// The IANA `mdns` service port, 5353.
    ///
    /// Multicast DNS
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 6762](https://datatracker.ietf.org/doc/html/rfc6762).
    @inlinable
    public static var mdns: Self {
        Port(canonicalValue: 5353)
    }

    /// The IANA `pmip6-cntl` service port, 5436.
    ///
    /// pmip6-cntl
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 5844](https://datatracker.ietf.org/doc/html/rfc5844).
    @inlinable
    public static var `pmip6-cntl`: Self {
        Port(canonicalValue: 5436)
    }

    /// The IANA `pmip6-data` service port, 5437.
    ///
    /// pmip6-data
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 5844](https://datatracker.ietf.org/doc/html/rfc5844).
    @inlinable
    public static var `pmip6-data`: Self {
        Port(canonicalValue: 5437)
    }

    /// The IANA `v5ua` service port, 5675.
    ///
    /// V5UA application port
    ///
    /// Registered for sctp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 3807](https://datatracker.ietf.org/doc/html/rfc3807).
    @inlinable
    public static var v5ua: Self {
        Port(canonicalValue: 5675)
    }

    /// The IANA `coap` service port, 5683.
    ///
    /// Constrained Application Protocol (CoAP)
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 7252](https://datatracker.ietf.org/doc/html/rfc7252) and
    /// [IETF RFC 8323](https://datatracker.ietf.org/doc/html/rfc8323).
    @inlinable
    public static var coap: Self {
        Port(canonicalValue: 5683)
    }

    /// The IANA `coaps` service port, 5684.
    ///
    /// Constrained Application Protocol (CoAP)
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 7252](https://datatracker.ietf.org/doc/html/rfc7252),
    /// [IETF RFC 7301](https://datatracker.ietf.org/doc/html/rfc7301) and
    /// [IETF RFC 8323](https://datatracker.ietf.org/doc/html/rfc8323).
    @inlinable
    public static var coaps: Self {
        Port(canonicalValue: 5684)
    }

    /// The IANA `diameters` service port, 5868.
    ///
    /// Diameter over TLS/TCP
    ///
    /// Registered for sctp and tcp transport protocols.
    ///
    /// Defined in [IETF RFC 6733](https://datatracker.ietf.org/doc/html/rfc6733).
    @inlinable
    public static var diameters: Self {
        Port(canonicalValue: 5868)
    }

    /// The IANA `rfb` service port, 5900.
    ///
    /// Remote Framebuffer
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 6143](https://datatracker.ietf.org/doc/html/rfc6143).
    @inlinable
    public static var rfb: Self {
        Port(canonicalValue: 5900)
    }

    /// The IANA `gsmp-ancp` service port, 6068.
    ///
    /// GSMP/ANCP
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 6320](https://datatracker.ietf.org/doc/html/rfc6320).
    @inlinable
    public static var `gsmp-ancp`: Self {
        Port(canonicalValue: 6068)
    }

    /// The IANA `geneve` service port, 6081.
    ///
    /// Generic Network Virtualization Encapsulation (Geneve)
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 8926](https://datatracker.ietf.org/doc/html/rfc8926).
    @inlinable
    public static var geneve: Self {
        Port(canonicalValue: 6081)
    }

    /// The IANA `reload-config` service port, 6084.
    ///
    /// Peer to Peer Infrastructure Configuration
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 6940](https://datatracker.ietf.org/doc/html/rfc6940).
    @inlinable
    public static var `reload-config`: Self {
        Port(canonicalValue: 6084)
    }

    /// The IANA `dccp-udp` service port, 6511.
    ///
    /// Datagram Congestion Control Protocol Encapsulation for NAT Traversal
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 6773](https://datatracker.ietf.org/doc/html/rfc6773).
    @inlinable
    public static var `dccp-udp`: Self {
        Port(canonicalValue: 6511)
    }

    /// The IANA `netconf-tls` service port, 6513.
    ///
    /// NETCONF over TLS
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 7589](https://datatracker.ietf.org/doc/html/rfc7589) and
    /// [IETF RFC 9918](https://datatracker.ietf.org/doc/html/rfc9918).
    @inlinable
    public static var `netconf-tls`: Self {
        Port(canonicalValue: 6513)
    }

    /// The IANA `syslog-tls` service port, 6514.
    ///
    /// Syslog over TLS
    ///
    /// Registered for dccp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5425](https://datatracker.ietf.org/doc/html/rfc5425) and
    /// [IETF RFC 6012](https://datatracker.ietf.org/doc/html/rfc6012).
    @inlinable
    public static var `syslog-tls`: Self {
        Port(canonicalValue: 6514)
    }

    /// The IANA `odette-ftps` service port, 6619.
    ///
    /// ODETTE-FTP over TLS/SSL
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 5024](https://datatracker.ietf.org/doc/html/rfc5024).
    @inlinable
    public static var `odette-ftps`: Self {
        Port(canonicalValue: 6619)
    }

    /// The IANA `mpls-udp` service port, 6635.
    ///
    /// Encapsulate MPLS packets in UDP tunnels.
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 7510](https://datatracker.ietf.org/doc/html/rfc7510).
    @inlinable
    public static var `mpls-udp`: Self {
        Port(canonicalValue: 6635)
    }

    /// The IANA `mpls-udp-dtls` service port, 6636.
    ///
    /// Encapsulate MPLS packets in UDP tunnels with DTLS.
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 7510](https://datatracker.ietf.org/doc/html/rfc7510).
    @inlinable
    public static var `mpls-udp-dtls`: Self {
        Port(canonicalValue: 6636)
    }

    /// The IANA `ovsdb` service port, 6640.
    ///
    /// Open vSwitch Database protocol
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 7047](https://datatracker.ietf.org/doc/html/rfc7047).
    @inlinable
    public static var ovsdb: Self {
        Port(canonicalValue: 6640)
    }

    /// The IANA `babel` service port, 6696.
    ///
    /// Babel Routing Protocol
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 8966](https://datatracker.ietf.org/doc/html/rfc8966).
    @inlinable
    public static var babel: Self {
        Port(canonicalValue: 6696)
    }

    /// The IANA `ircs-u` service port, 6697.
    ///
    /// Internet Relay Chat via TLS/SSL
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 7194](https://datatracker.ietf.org/doc/html/rfc7194).
    @inlinable
    public static var `ircs-u`: Self {
        Port(canonicalValue: 6697)
    }

    /// The IANA `babel-dtls` service port, 6699.
    ///
    /// Babel Routing Protocol over DTLS
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 8968](https://datatracker.ietf.org/doc/html/rfc8968).
    @inlinable
    public static var `babel-dtls`: Self {
        Port(canonicalValue: 6699)
    }

    /// The IANA `frc-hp` service port, 6704.
    ///
    /// ForCES HP (High Priority) channel
    ///
    /// Registered for sctp transport protocol.
    ///
    /// Defined in [IETF RFC 5811](https://datatracker.ietf.org/doc/html/rfc5811).
    @inlinable
    public static var `frc-hp`: Self {
        Port(canonicalValue: 6704)
    }

    /// The IANA `frc-mp` service port, 6705.
    ///
    /// ForCES MP (Medium Priority) channel
    ///
    /// Registered for sctp transport protocol.
    ///
    /// Defined in [IETF RFC 5811](https://datatracker.ietf.org/doc/html/rfc5811).
    @inlinable
    public static var `frc-mp`: Self {
        Port(canonicalValue: 6705)
    }

    /// The IANA `frc-lp` service port, 6706.
    ///
    /// ForCES LP (Low priority) channel
    ///
    /// Registered for sctp transport protocol.
    ///
    /// Defined in [IETF RFC 5811](https://datatracker.ietf.org/doc/html/rfc5811).
    @inlinable
    public static var `frc-lp`: Self {
        Port(canonicalValue: 6706)
    }

    /// The IANA `bfd-lag` service port, 6784.
    ///
    /// Bidirectional Forwarding Detection (BFD) on Link Aggregation Group (LAG) Interfaces
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 7130](https://datatracker.ietf.org/doc/html/rfc7130).
    @inlinable
    public static var `bfd-lag`: Self {
        Port(canonicalValue: 6784)
    }

    /// The IANA `grasp` service port, 7017.
    ///
    /// GeneRic Autonomic Signaling Protocol
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 8990](https://datatracker.ietf.org/doc/html/rfc8990).
    @inlinable
    public static var grasp: Self {
        Port(canonicalValue: 7017)
    }

    /// The IANA `cfw` service port, 7563.
    ///
    /// Control Framework
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 6230](https://datatracker.ietf.org/doc/html/rfc6230).
    @inlinable
    public static var cfw: Self {
        Port(canonicalValue: 7563)
    }

    /// The IANA `simco` service port, 7626.
    ///
    /// SImple Middlebox COnfiguration (SIMCO) Server
    ///
    /// Registered for sctp and tcp transport protocols.
    ///
    /// Defined in [IETF RFC 4540](https://datatracker.ietf.org/doc/html/rfc4540).
    @inlinable
    public static var simco: Self {
        Port(canonicalValue: 7626)
    }

    /// The IANA `raqmon-pdu` service port, 7744.
    ///
    /// RAQMON PDU
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 4712](https://datatracker.ietf.org/doc/html/rfc4712).
    @inlinable
    public static var `raqmon-pdu`: Self {
        Port(canonicalValue: 7744)
    }

    /// The IANA `s-bfd` service port, 7784.
    ///
    /// Seamless Bidirectional Forwarding Detection (S-BFD)
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 7881](https://datatracker.ietf.org/doc/html/rfc7881).
    @inlinable
    public static var `s-bfd`: Self {
        Port(canonicalValue: 7784)
    }

    /// The IANA `mipv6tls` service port, 7872.
    ///
    /// TLS-based Mobile IPv6 Security
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 6618](https://datatracker.ietf.org/doc/html/rfc6618).
    @inlinable
    public static var mipv6tls: Self {
        Port(canonicalValue: 7872)
    }

    /// The IANA `aero` service port, 8060.
    ///
    /// Asymmetric Extended Route Optimization (AERO)
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 6706](https://datatracker.ietf.org/doc/html/rfc6706).
    @inlinable
    public static var aero: Self {
        Port(canonicalValue: 8060)
    }

    /// The IANA `hncp-udp-port` service port, 8231.
    ///
    /// HNCP
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 7788](https://datatracker.ietf.org/doc/html/rfc7788).
    @inlinable
    public static var `hncp-udp-port`: Self {
        Port(canonicalValue: 8231)
    }

    /// The IANA `hncp-dtls-port` service port, 8232.
    ///
    /// HNCP over DTLS
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 7788](https://datatracker.ietf.org/doc/html/rfc7788).
    @inlinable
    public static var `hncp-dtls-port`: Self {
        Port(canonicalValue: 8232)
    }

    /// The IANA `pim-port` service port, 8471.
    ///
    /// PIM over Reliable Transport
    ///
    /// Registered for sctp and tcp transport protocols.
    ///
    /// Defined in [IETF RFC 6559](https://datatracker.ietf.org/doc/html/rfc6559).
    @inlinable
    public static var `pim-port`: Self {
        Port(canonicalValue: 8471)
    }

    /// The IANA `lsp-self-ping` service port, 8503.
    ///
    /// MPLS LSP Self-Ping
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 7746](https://datatracker.ietf.org/doc/html/rfc7746).
    @inlinable
    public static var `lsp-self-ping`: Self {
        Port(canonicalValue: 8503)
    }

    /// The IANA `sapv1` service port, 9875.
    ///
    /// Session Announcement v1
    ///
    /// Registered for tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 2974](https://datatracker.ietf.org/doc/html/rfc2974).
    @inlinable
    public static var sapv1: Self {
        Port(canonicalValue: 9875)
    }

    /// The IANA `kca-service` service port, 9878.
    ///
    /// The KX509 Kerberized Certificate Issuance Protocol in Use in 2012
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 6717](https://datatracker.ietf.org/doc/html/rfc6717).
    @inlinable
    public static var `kca-service`: Self {
        Port(canonicalValue: 9878)
    }

    /// The IANA `sctp-tunneling` service port, 9899.
    ///
    /// SCTP TUNNELING
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 6951](https://datatracker.ietf.org/doc/html/rfc6951).
    @inlinable
    public static var `sctp-tunneling`: Self {
        Port(canonicalValue: 9899)
    }

    /// The IANA `enrp-sctp` service port, 9901.
    ///
    /// enrp server channel
    ///
    /// Registered for sctp transport protocol.
    ///
    /// Defined in [IETF RFC 5353](https://datatracker.ietf.org/doc/html/rfc5353).
    @inlinable
    public static var `enrp-sctp`: Self {
        Port(canonicalValue: 9901)
    }

    /// The IANA `enrp-sctp-tls` service port, 9902.
    ///
    /// enrp/tls server channel
    ///
    /// Registered for sctp transport protocol.
    ///
    /// Defined in [IETF RFC 5353](https://datatracker.ietf.org/doc/html/rfc5353).
    @inlinable
    public static var `enrp-sctp-tls`: Self {
        Port(canonicalValue: 9902)
    }

    /// The IANA `multicast-ping` service port, 9903.
    ///
    /// Multicast Ping Protocol
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 6450](https://datatracker.ietf.org/doc/html/rfc6450).
    @inlinable
    public static var `multicast-ping`: Self {
        Port(canonicalValue: 9903)
    }

    /// The IANA `snmpdtls` service port, 10161.
    ///
    /// SNMP-DTLS
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 6353](https://datatracker.ietf.org/doc/html/rfc6353).
    @inlinable
    public static var snmpdtls: Self {
        Port(canonicalValue: 10161)
    }

    /// The IANA `snmptls` service port, 10161.
    ///
    /// SNMP-TLS
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 6353](https://datatracker.ietf.org/doc/html/rfc6353).
    @inlinable
    public static var snmptls: Self {
        Port(canonicalValue: 10161)
    }

    /// The IANA `snmpdtls-trap` service port, 10162.
    ///
    /// SNMP-Trap-DTLS
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 6353](https://datatracker.ietf.org/doc/html/rfc6353).
    @inlinable
    public static var `snmpdtls-trap`: Self {
        Port(canonicalValue: 10162)
    }

    /// The IANA `snmptls-trap` service port, 10162.
    ///
    /// SNMP-Trap-TLS
    ///
    /// Registered for tcp transport protocol.
    ///
    /// Defined in [IETF RFC 6353](https://datatracker.ietf.org/doc/html/rfc6353).
    @inlinable
    public static var `snmptls-trap`: Self {
        Port(canonicalValue: 10162)
    }

    /// The IANA `hip-nat-t` service port, 10500.
    ///
    /// HIP NAT-Traversal
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 5770](https://datatracker.ietf.org/doc/html/rfc5770) and
    /// [IETF RFC 9028](https://datatracker.ietf.org/doc/html/rfc9028).
    @inlinable
    public static var `hip-nat-t`: Self {
        Port(canonicalValue: 10500)
    }

    /// The IANA `nfsrdma` service port, 20049.
    ///
    /// Network File System (NFS) over RDMA
    ///
    /// Registered for sctp, tcp and udp transport protocols.
    ///
    /// Defined in [IETF RFC 8267](https://datatracker.ietf.org/doc/html/rfc8267).
    @inlinable
    public static var nfsrdma: Self {
        Port(canonicalValue: 20049)
    }

    /// The IANA `udpstp` service port, 24601.
    ///
    /// UDP-based IP-Layer Capacity and Performance Measurement protocol
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 9946](https://datatracker.ietf.org/doc/html/rfc9946).
    @inlinable
    public static var udpstp: Self {
        Port(canonicalValue: 24601)
    }

    /// The IANA `mtrace` service port, 33435.
    ///
    /// IP Multicast Traceroute
    ///
    /// Registered for udp transport protocol.
    ///
    /// Defined in [IETF RFC 8487](https://datatracker.ietf.org/doc/html/rfc8487).
    @inlinable
    public static var mtrace: Self {
        Port(canonicalValue: 33435)
    }
}
